### ISSUE TITLE
[1.12.2] actually-additions disruption-lens mixin crash

### ISSUE THREAD

**Issue by MasterEnderman** [LXGaming/Sledgehammer#49] opened 2023-10-21 17:36 UTC
Forge: 14.23.5.2860
Sledgehammer: 2.0.24
Crash-Report: https://gist.github.com/MasterEnderman/671b085a1771af48b01166285d46459b

**Comment by LXGaming** [comment] 2023-10-22 02:39
Issue reproduced, Looks like something went wrong during the build process which caused `getStackInSlot` to be wrongly obfuscated to `func_70301_a`, I'm currently tracking down the issue.

The affected builds have been pulled.

UPDATE: There might be a race condition in [ForgeAutoRenamingTool](https://github.com/MinecraftForge/ForgeAutoRenamingTool), will have to do more investigation but an quick fix might be to limit it to a single thread.

**Comment by LXGaming** [comment] 2023-10-22 09:33
Fixed in [v1.12.2-2.0.25](https://github.com/LXGaming/Sledgehammer/releases/tag/v1.12.2-2.0.25)

**Closed as completed by LXGaming** 2023-10-22 09:33 UTC
