### ISSUE TITLE
Startup Crash

### ISSUE THREAD

**Issue by ghost** [LXGaming/Sledgehammer#11] opened 2020-02-10 01:50 UTC
Version 1.12.2-2.0.0 crashes on startup with the attached log. I just downgraded versions and now everything is fine again on my end, but I figured this would be good for you to know. The stacktrace seems to frequently mention foamfix.

[log](https://pastebin.com/VAepcNi2)

**Comment by LXGaming** [comment] 2020-02-10 01:56
Please re-test with https://www.curseforge.com/minecraft/mc-mods/sledgehammer/files/2877349
This version uses Mixin 0.7 rather than Mixin 0.8.

**Comment by Sunconure11** [comment] 2020-02-12 10:36
Has anyone tested this at all?

**Comment by Sunconure11** [comment] 2020-02-12 11:56
Okay, so I've tested it, and with this build, it boots up.

**Comment by LXGaming** [comment] 2020-02-12 12:36
The original log contains a `java.lang.NoSuchMethodError` which is caused by Sledgehammer trying to access a Mixin 0.8 method which isn't present due to Mixin 0.7 getting loaded by another mod.

The fix for this is to use Sledgehammer builds which are specifically for Mixin 0.7 (These builds contain 0.7 in the file name).

If you still encounter issues after switching builds then please make an issue or comment with the latest `debug.log` file.

**Closed as completed by LXGaming** 2020-02-12 12:36 UTC

**Comment by Sunconure11** [comment] 2020-02-12 16:26
Could you publish a build of sledgehammer with mixin 0.7 as the next build, mainly to deal with twitch stupidity?

**Comment by Sunconure11** [comment] 2020-02-13 14:04
And by publish, I mean a build that does not count as just an additional file?

Also, I've been told mixin 0.8 is for 1.14+ anyways

**Comment by LXGaming** [comment] 2020-02-13 14:10
I wasn't aware that Twitch had issues handling additional files so I'll look into separating the files on Curse.

SpongeForge for 1.12.2 has updated to Mixin 0.8 hence why multiple builds exist.

**Comment by Sunconure11** [comment] 2020-02-14 15:19
Any news on this?

**Comment by LXGaming** [comment] 2020-02-15 00:07
@Sunconure11 https://www.curseforge.com/minecraft/mc-mods/sledgehammer/files/2881852

**Comment by Sunconure11** [comment] 2020-03-30 12:05
Might want to publish a build, set it as a separate file as opposed to being an additional file under another existing build. (so just upload a new build to curse directly)

More stuff is updating to 0.8 now so that build no longer works.

**Comment by LXGaming** [comment] 2020-03-30 12:10
They are already separate?

Mixin 0.7: https://www.curseforge.com/minecraft/mc-mods/sledgehammer/files/2894584

Mixin 0.8: https://www.curseforge.com/minecraft/mc-mods/sledgehammer/files/2894582
