### ISSUE TITLE
[suggestion] migrate to MixinBooter

### ISSUE THREAD

**Issue by kappa-maintainer** [LXGaming/Sledgehammer#51] opened 2024-04-09 13:51 UTC
Current mod mixin rely on a hack to `Loader` that could easily fail if another mod is doing similar things.
In fact, it's now incompatible with [Cleanroom](https://github.com/CleanroomMC/Cleanroom).
You can:
- Use MixinBooter's `LateMixin`
- Or use `@env(MOD)` (will make the mod Cleanroom only)
- Or add mod mixin configs manually in `net.minecraftforge.fml.common.LoadController#distributeStateMessage(net.minecraftforge.fml.common.LoaderState, java.lang.Object...)`

**Comment by LXGaming** [comment] 2024-04-09 14:38
What exactly is Cleanroom? It looks interesting but it seems to be a Mod Loader not a Mod as indicated above.

I'll look into this when I get a chance.

**Comment by kappa-maintainer** [comment] 2024-04-09 15:58
It's a mod loader I am working on, but a lot of players are reporting incompat with sledgehammer
After some investigation I realized patching sledgehammer's Mixin config is too hackery so I decided to open issue here

**Comment by LXGaming** [comment] 2024-04-15 04:43
So I believe the `Loader` incompatibility is actually caused by the `mixin.initialised` key being changed to `mixin:initialised` in [kappa-maintainer/Mixin](https://github.com/kappa-maintainer/Mixin/blob/main/src/main/java/org/spongepowered/asm/launch/GlobalProperties.java#L45), this prevented Sledgehammer from detecting if Mixin had been loaded early enough which stopped the `mixins.sledgehammer.preinit.json` from being added which is what contains the `LoaderMixin`, The key is hardcoded for backwards compatibility with Mixin 0.7.

In any case I've added optional MixinBooter support (Both Cleanroom and Forge mod), if it's detected during launch then the `LoaderMixin` is not loaded and instead the all additional mixin configs are loaded by an `ILateMixinLoader`.

Fixed in [v1.12.2-2.0.26](https://github.com/LXGaming/Sledgehammer/releases/tag/v1.12.2-2.0.26), please let me know if players are still having incompatibility issues.

**Comment by kappa-maintainer** [comment] 2024-04-15 07:47
So it *was* our fault
The unfinished key change was for making it a bit of resource location style, we never expected some other mods is checking it
I will check the new version asap

**Closed as completed** 2024-04-16 13:59 UTC
